from .combo import bp as combo_bp
from .compare import bp as compare_bp
from .employee import bp as employee_bp
from .employer import bp as employer_bp
from .home import bp as home_bp
from .pages import bp as pages_bp
from .position import bp as position_bp
from .sector import bp as sector_bp
from .top_earners import bp as top_earners_bp
